### ISSUE TITLE
QR codes generated aren't read by my android Barcode Scanner app

### ISSUE THREAD

**Issue by aaronscientiae** [xyzzy/qrpicture#1]
I tried to read the barcode I generated or the others at the top of the website with an android app "Barcode Scanner" 4.7.8 by ZXing team. and it wouldn't see it as a qr code or anything. It kept searching for points. I had it on my desktop with the phone pointed at it.

**Comment by gerroon** [comment]
This does not work for me either. I tried Barcode Scanner and Binary Eye on Android.

**Comment by xyzzy** [comment]
I tried the app, and it works.... sometimes. I think what is happening is that the app has such a tiny viewport forcing you to hold the camera at such a distance that the pixels aren't differentiating. The app also has great difficulty to set focus. I use QRdroid and that has 100% success rate.

This isn't something I can fix so I sadly have to close the issue.
