### ISSUE TITLE
Generated images 404 on live site

### ISSUE THREAD

**Issue by easrng** [xyzzy/qrpicture#2]
[Here's a video of the behavior.](https://github.com/xyzzy/qrpicture/files/5077571/2020-08-14_18-11-12.zip) (Zipped because github doesn't like videos)

**Comment by xyzzy** [comment]
The 404 happens when there is insufficient contrast in the picture. 

I'm working on moving functionality from C to Javascript so it can be tweaked and corrected with the preview.
