### ISSUE TITLE
Clip stage unusable on Android

### ISSUE THREAD

**Issue by JonnyTech** [xyzzy/qrpicture#3]
When using my Android device with Fennec (Firefox) browser to generate a QRpicture, I am unable to resize the clip box - trying to move the drag handles just drags the whole page around.

**Comment by xyzzy** [comment]
Ah, I see what you mean. 

I updated to mootools 1.6.0 hoping it would fix the situation. It didn't.
Digging deeper into the issue.

**Comment by xyzzy** [comment]
This should be solved with release 1.2.0.
