### ISSUE TITLE
unable to build: ./configure not available?

### ISSUE THREAD

**Issue by wivaku** [xyzzy/qrpicture#5]
Build instructions say:

> Configure and set prefix to document root
> 
> 	./configure --prefix=<documentroot>

I assume the first step is: `autoconf` (as there is no `./configure`)

After I run `autoconf` and then `./configure` I get:

```
./configure --prefix=/www/qrpicture
configure: error: cannot find install-sh, install.sh, or shtool in m4 "."/m4
```

**Comment by xyzzy** [comment]
git does not support configure.

If you cloned the archive there is a script `autogen.sh` which (re-)constructs the configure framework.
Alternatively, I also uploaded a pre-constructed configure `tar.gz`to the release repository.

https://github.com/xyzzy/qrpicture/releases/download/v1.0.0/qrpicture-1.0.0.tar.gz

I will also include `autogen.sh` in the README to avoid future confusion.
